#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running linter..."
if ! npm run lint; then
    echo "Linting failed. Commit aborted."
    exit 1
fi

echo "Linting passed. Proceeding with commit."